name: Validate Tags

on:
  push:
  pull_request:

permissions:
  packages: read

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run -v $(pwd)/tags:/tags ghcr.io/fabricmc/fabric-discord-bot:tags-latest
